# docker-compose.yml
services:
  web:
    image: mission-web:1.1
    ports:
      - "8080:80"
    # environment : 컨테이너 안에 환경 변수 주입
    #   Dockerfile의 ENV와 달리, 실행 시점에 동적으로 값을 바꿀 수 있음
    environment:
      - APP_ENV=development
      - APP_PORT=80
